DROP DATABASE IF EXISTS MY_FINANCIAL_PICTURE;
CREATE DATABASE MY_FINANCIAL_PICTURE;
USE MY_FINANCIAL_PICTURE;
--Skeleton Structure for My Financial Picture Database
CREATE TABLE USERS (
    ID INT NOT NULL PRIMARY KEY,
    EMAIL VARCHAR(50),
    PASSWORD_HASH VARCHAR(50),
    CREATED_AT VARCHAR(50),
    LAST_LOGIN VARCHAR(50)
);

CREATE TABLE BUDGETS (
    ID INT NOT NULL PRIMARY KEY,
    USER_ID INT NOT NULL,
    CATEGORY_ID INT NOT NULL,
    LIMIT_AMOUNT VARCHAR(50) NOT NULL,
    START_DATE VARCHAR(50) NOT NULL,
    END_DATE VARCHAR(50) NOT NULL,
    DESCRIPTION_ VARCHAR(50) NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

CREATE TABLE TRANSACTIONSTL (
    ID INT NOT NULL PRIMARY KEY,
    ACCOUNT_ID INT NOT NULL,
    NAME_ VARCHAR(50),
    IS_CATEGORY VARCHAR(50),
    DATE_ VARCHAR(50),
    TYPE_ VARCHAR(50),
    IS_RECURRING VARCHAR(50),
    CREATED_AT VARCHAR(50)
);

CREATE TABLE TRANSACTIONS (
    ID INT NOT NULL PRIMARY KEY,
    ACCOUNT_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    CATEGORY_ID INT NOT NULL, 
    AMOUNT_ INT,
    DESCRIPTION_ VARCHAR(50),
    DATE_ VARCHAR(50),
    TYPE_ VARCHAR(50),
    IS_RECURRING VARCHAR(50),
    CREATED_AT VARCHAR(50),
    FOREIGN KEY (CATEGORY_ID) REFERENCES TRANSACTIONSTL(ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

CREATE TABLE INSTITUTIONS (
    ID INT NOT NULL PRIMARY KEY,
    USER_V_ID INT NOT NULL,
    NAME VARCHAR(50),
    TYPE VARCHAR(50),
    BALANCE INT,
    CURRENCY VARCHAR(50),
    CREATED_AT VARCHAR(50),
    FOREIGN KEY (USER_V_ID) REFERENCES USERS(ID)
);

CREATE TABLE GOALSTL (
    ID INT NOT NULL PRIMARY KEY,
    USER_ID INT NOT NULL,
    NAME_ VARCHAR(50),
    TARGET_AMOUNT INT NOT NULL,
    CURRENT_AMOUNT INT NOT NULL,
    DEADLINE VARCHAR(50),
    DESCRIPTION_ VARCHAR(50),
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

CREATE TABLE GOALS (
    ID INT NOT NULL PRIMARY KEY,
    USER_ID INT NOT NULL,
    NAME_ VARCHAR(50),
    TARGET_AMOUNT INT NOT NULL,
    DEADLINE VARCHAR(50),
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);
