DROP DATABASE IF EXISTS MY_FINANCIAL_PICTURE;
CREATE DATABASE MY_FINANCIAL_PICTURE;
USE MY_FINANCIAL_PICTURE;
CREATE TABLE USERS (
	ID INT NOT NULL PRIMARY KEY,
    EMAIL VARCHAR(50),
    PASSWORD_HASH VARCHAR(50),
    CREATED_AT VARCHAR(50),
    LAST_LOGIN VARCHAR(50)
    );
CREATE TABLE INSTITUTIONS (
	ID INT NOT NULL PRIMARY KEY,
    USER_V_ID INT NOT NULL,
    INSTITUTION_ID INT NOT NULL,
    NAME VARCHAR(50),
    TYPE VARCHAR(50),
    BALANCE INT,
    CURRENCY VARCHAR(50),
    CREATED_AT VARCHAR(50),
    FOREIGN KEY (USER_V_ID) REFERENCES USERS(ID),
    FOREIGN KEY(INSTITUTION_ID) REFERENCES TRANSACTIONS(ID)
    );
CREATE TABLE TRANSACTIONS (
	ID INT NOT NULL PRIMARY KEY,
    ACCOUNT_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    CATEGORY_ID INT NOT NULL, 
    AMOUNT_ INT,
    DESCRIPTION_ VARCHAR(50),
    DATE_ VARCHAR(50),
    TYPE_ VARCHAR(50),
    IS_RECURRING VARCHAR(50),
    CREATED_AT VARCHAR(50),
    FOREIGN KEY (CATEGORY_ID) REFERENCES TRANSACTIONS(CATEGORY_ID),
    FOREIGN KEY (ACCOUNT_ID) REFERENCES 
    );
CREATE TABLE BUDGETS (
	ID INT NOT NULL,
    USER_ID INT NOT NULL,
    CATEGORY_ID INT NOT NULL,
    TIMIT_AMEUN VARCHAR(50) NOT NULL,
    START_DATE VARCHAR(50) NOT NULL,
    END_DATE VARCHAR(50) NOT NULL,
    DESCRIPTION_ VARCHAR(50) NOT NULL,
    );
CREATE  TABLE TRANSACTIONSTL (
	ID INT NOT NULL,
    ACCOUNT_ID INT NOT NULL,
    NAME_ VARCHAR(50),
    IS_CRAGONY VARCHAR(50),
    DATE_ VARCHAR(50),
    TYPE_ VARCHAR(50),
    IS_RECURRING VARCHAR(50),
    CREATED_AT VARCHAR(50)
    );
CREATE TABLE GOALSTL (
	ID INT NOT NULL,
    USER_ID INT NOT NULL,
    NAME_ VARCHAR(50),
    TARGET_AMOUNT INT NOT NULL,
    CURRENT_AMOUNT INT NOT NULL,
    DEADLINE VARCHAR(50),
    DESCRIPTION_ VARCHAR(50)
    );
CREATE TABLE GOALS (
	ID INT NOT NULL,
    USER_ID INT NOT NULL,
    NAME_ VARCHAR(50),
    TARGET_AMOUNT INT NOT NULL,
    DEADLINE VARCHAR(50)
    );
    
	
    
    
