services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    command: uvicorn backend:app --host 0.0.0.0 --port 8000 --reload