name: Backend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-backend:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: jay
          MYSQL_DATABASE: MY_FINANCIAL_PICTURE
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn pytest mysql-connector-python passlib python-dotenv httpx
          pip install -r requirements.txt


      - name: Wait for MySQL to be ready
        run: |
          echo "⏳ Waiting for MySQL to start..."
          for i in {1..30}; do
            if mysqladmin ping -h 127.0.0.1 -P 3306 --silent; then
              echo "MySQL is running!"
              break
            fi
            echo "MySQL not ready yet... retrying ($i/30)"
            sleep 2
          done


      - name: Run backend tests
        env:
          DB_HOST: mfp-db-dev.cj0mg2aea2ln.us-east-2.rds.amazonaws.com
          DB_USER: jay
          DB_PASSWORD: jay
          DB_NAME: MY_FINANCIAL_PICTURE
        run: |
          pytest backend/
