name: Backend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-backend:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: MY_FINANCIAL_PICTURE_TEST
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn pytest mysql-connector-python passlib python-dotenv httpx

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL to start..."
          sleep 20  # simple wait; could also use a loop to check health

      - name: Run backend tests
        env:
          DB_HOST: 127.0.0.1
          DB_USER: root
          DB_PASSWORD: password
          DB_NAME: MY_FINANCIAL_PICTURE_TEST
        run: |
          pytest tests/ --maxfail=1 --disable-warnings -q
