name: Frontend CI

on:
  push:
    paths:
      - 'My-Financial-Picture/**'
      - '.github/workflows/frontend-ci.yml'
  pull_request:
    paths:
      - 'My-Financial-Picture/**'

jobs:
  test-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: My-Financial-Picture
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'My-Financial-Picture/package-lock.json'

      - run: npm ci
      - run: npm run lint --if-present
      - run: npm run test -- --run
      - run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: My-Financial-Picture/dist
