name: Frontend Deploy (GitHub Pages)

on:
  push:
    branches: [ "main" ]
    paths:
      - 'My-Financial-Picture/**'
      - '.github/workflows/frontend-deploy-pages.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: My-Financial-Picture
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'My-Financial-Picture/package-lock.json'

      - run: npm ci
      - run: echo "GITHUB_PAGES=true" >> $GITHUB_ENV
      - run: npm run build

      # SPA fallback so react-router routes don't 404 on refresh
      - run: cp dist/index.html dist/404.html

      - uses: actions/upload-pages-artifact@v3
        with:
          path: My-Financial-Picture/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
